### ISSUE TITLE
Missing module 'glob'

### ISSUE THREAD

**Issue by manor** [webix-hub/wjet#7]
This transcript says it all:
```
~/ : mkdir test
~/ : cd test
~/ : node -v
v5.4.1
~/ : npm -v
3.5.3
~/ : wjet init
? Give your app a name tester
? Do you want to create a multi-language app? No
? Do you want to use multiple skins? No
? Css pre-processor? None
/usr/local/lib/node_modules/wjet/templates/noserver
/usr/local/lib/node_modules/wjet/templates/extras/css
/usr/local/lib/node_modules/wjet/templates/extras/css/assets
/usr/local/lib/node_modules/wjet/templates/noserver/.bowerrc
/usr/local/lib/node_modules/wjet/templates/extras/css/assets/app.css
/usr/local/lib/node_modules/wjet/templates/noserver/.npmignore
/usr/local/lib/node_modules/wjet/templates/noserver/README.md
/usr/local/lib/node_modules/wjet/templates/noserver/app.js
/usr/local/lib/node_modules/wjet/templates/noserver/bower.json
/usr/local/lib/node_modules/wjet/templates/noserver/gulpfile.js
/usr/local/lib/node_modules/wjet/templates/noserver/index.html
/usr/local/lib/node_modules/wjet/templates/noserver/jshint.conf.js
/usr/local/lib/node_modules/wjet/templates/noserver/models
/usr/local/lib/node_modules/wjet/templates/noserver/package.json
/usr/local/lib/node_modules/wjet/templates/noserver/views
/usr/local/lib/node_modules/wjet/templates/noserver/models/records.js
/usr/local/lib/node_modules/wjet/templates/noserver/views/data.js
/usr/local/lib/node_modules/wjet/templates/noserver/views/start.js
/usr/local/lib/node_modules/wjet/templates/noserver/views/top.js
Insaling dependencies...
done
~/ : gulp init
module.js:327
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/manor/test/gulpfile.js:4:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by mkozhukh** [comment]
Updated version install npm dependencies automatically
